GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/60f3b97d8a4a161468af197b

### 

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Juan Luna",
    "subscribedTo": "Web Dev Simplified"
}

###
DELETE http://localhost:3000/subscribers/60f3b97d8a4a161468af197b